version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: siconvis_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: siconvis
      MYSQL_USER: siconvis
      MYSQL_PASSWORD: siconvis123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    networks:
      - siconvis_network

  # Backend PHP
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siconvis_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/uploads:/var/www/html/uploads
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=siconvis
      - DB_USERNAME=siconvis
      - DB_PASSWORD=siconvis123
    depends_on:
      - mysql
    networks:
      - siconvis_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: siconvis_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - siconvis_network

  # phpMyAdmin para gestión de base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: siconvis_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - siconvis_network

volumes:
  mysql_data:

networks:
  siconvis_network:
    driver: bridge
